### ISSUE TITLE
Black text on yellow and light blue backgrounds

### ISSUE THREAD

**Issue by retnikt** [devBanner/devBanner#12]
On avatars with yellow and light blue backgrounds, the text should be black so it's more readable

**Comment by Kimmax** [comment]
Agreed

**Comment by cozyplanes** [comment]
light blue is fine, i guess..

Will definitely do for yellow ones. (there is yellow?)

**Comment by cozyplanes** [comment]
I feel this is unnecessary. Black in yellow doesn't seem to fit together
Thoughts? @Kimmax

**Comment by cozyplanes** [comment]
Fixed!
