### ISSUE TITLE
Unicode 10 support. (Emoji 5.0)

### ISSUE THREAD

**Issue by olback** [devBanner/devBanner#38]
Emojis doesn't work as you can see in the image. I guess this is due to the font, could be wrong though. Having Unicode 10 support would allow (almost?) all characters in the world.
I have no idea how hard it would be to implement and I guess it's not that important.
Label with Low priority.

![screenshot_20180113-161544](https://user-images.githubusercontent.com/8039145/34907375-dd9aba36-f87d-11e7-9de8-9bd927febb4c.jpg)

**Comment by cozyplanes** [comment]
Our font currently has no emoji support. Sorry for that. You can see the supported characters here.
https://fonts.google.com/specimen/Comfortaa

Will close for now, and will open later when we have plans to implement this. 
Thanks for the interest!

**Comment by Kimmax** [comment]
Maybe I could render emoijs using a fallback font, but that would require looking at each character one by one. Maybe we can add the emoijs to the ttf directly.. Maybe we don't need emoijs
