### ISSUE TITLE
Text Needs To Wrap

### ISSUE THREAD

**Issue by LoganS1** [devBanner/devBanner#4]
Text that is too long needs to wrap around, currently it just goes offscreen

**Comment by cozyplanes** [comment]
Will fix that soon, thanks

**Comment by Kimmax** [comment]
For word wrapping we need to measure the rendered text and determine if it needs to wrap.
If so we should be able to split at the last word and continue until the text fits.
That's the quick and dirty way, I'm sure there's a better one.
Also we should build in some kind of character limit for the subtext
