### ISSUE TITLE
Long names get cut off

### ISSUE THREAD

**Issue by CorruptComputer** [devBanner/devBanner#40]
![image](https://user-images.githubusercontent.com/5573038/35163789-895573d2-fd0d-11e7-88d3-a2c834c19960.png)

**Comment by Kimmax** [comment]
Looks like we need to apply my initial scaling patch here

**Comment by cozyplanes** [comment]
Oops!

**Comment by cozyplanes** [comment]
Fixed by commit https://github.com/devBanner/devBanner/commit/92ed56da9c196e28f2a3b64df6453b18aa1b9dce
