### ISSUE TITLE
Word wrap is a bit broken

### ISSUE THREAD

**Issue by cozyplanes** [devBanner/devBanner#46]
@Mitch528 
typing the following
```
I made the unofficial devRant client for Windows 10.
```
in subtext, the `10.` doesn't get wrapped

the font size has been changed (to a smaller font size)
see the latest commit https://github.com/devBanner/devBanner/commit/92ed56da9c196e28f2a3b64df6453b18aa1b9dce

**Comment by cozyplanes** [comment]
@Etnath Can you?

**Comment by Etnath** [comment]
@cozyplanes I can reproduce the problem.

![bugdevbanner](https://user-images.githubusercontent.com/7302166/42480534-8db6b280-8410-11e8-8547-ae1fc0c15e9c.png)

I will look into it.

**Comment by cozyplanes** [comment]
Thanks

**Comment by cozyplanes** [comment]
#47
