### ISSUE TITLE
Subtext missing creates layout issue

### ISSUE THREAD

**Issue by cozyplanes** [devBanner/devBanner#9]
If no subtext is being provided, the description of profile gets written behind the username

![](https://i.imgur.com/7QoESTs.png)

**Comment by Kimmax** [comment]
Non defined subtext falls back to the user about text. I suspect this is too big 90% of the time
I think I'll make the subtext mandatory

**Comment by Kimmax** [comment]
Well "fixed" in #11, however it will now scale the font down until the text fits.
This is going to be handled in the word wrap update

**Comment by cozyplanes** [comment]
Seems that it is fixed, but has another issue . will open another one.
